name: Python CI

on:
  push:
    branches:
      - main   # Trigger the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main   # Also trigger the workflow on pull requests to main
  
jobs:
  test:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9 (you can change this version if necessary)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements file

      - name: Run tests with pytest
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/A-star/src pytest -v   # Run the tests with pytest and show verbose output
